console.log(Math.abs(-20));
console.log(Math.acos(-20));
console.log(Math.acosh(-20));
console.log(Math.asin(-20));
console.log(Math.asinh(-20));
console.log(Math.atan(-20));
console.log(Math.atan2(-20, -20));
console.log(Math.atanh(-20));
console.log(Math.cbrt(-20));
console.log(Math.ceil(-20));
console.log(Math.clz32(-20));
console.log(Math.cos(-20));
console.log(Math.cosh(-20));
console.log(Math.exp(-20));
console.log(Math.expm1(-20));
console.log(Math.floor(-20));
console.log(Math.hypot(-20));
console.log(Math.imul(-20, 2));
console.log(Math.log(20));
console.log(Math.log10(20));
console.log(Math.log1p(20));
console.log(Math.log2(20));
console.log(Math.max(-20, 10));
console.log(Math.min(-20, 10));
console.log(Math.pow(-20, 2));
console.log(Math.random());
console.log(Math.round(-20));
console.log(Math.sign(-20));
console.log(Math.sin(20));
console.log(Math.sinh(20));
console.log(Math.sqrt(20));
console.log(Math.tan(20));
console.log(Math.tanh(20));
console.log(Math.trunc(20));
