//--------------------------------------------------------------------------------------------------
// Copyright (C) Moonly Days                                                                       -
// https://github.com/MoonlyDays                                                                   -
//--------------------------------------------------------------------------------------------------

export {};

declare global {
    const Convars: CConVars;
}

declare interface CConVars {
    /**
     * Returns the convar as a bool. May return null if no such convar.
     */
    GetBool(name: ConVarNames): boolean;

    /**
     * Returns the convar value for the entindex as a string. Only works on client convars with the FCVAR_USERINFO flag.
     * @tip The list of available client convars can be printed in console using the findflags USERINFO command.
     * @param name
     * @param entindex
     */
    GetClientConvarValue(name: ConVarNames, entindex: number): string | null;

    /**
     * Returns the convar as an int. May return null if no such convar.
     * @param name
     */
    GetInt(name: ConVarNames): number | null;

    /**
     * Returns the convar as a string. May return null if no such convar.
     * @param name
     */
    GetStr(name: ConVarNames): string | null;

    /**
     * Returns the convar as a float. May return null if no such convar.
     * @param name
     */
    GetFloat(name: ConVarNames): number | null;

    /**
     * Checks if the convar is allowed to be used and is in cfg/vscript_convar_allowlist.txt. Please be nice with this
     * and use it for *compatibility* if you need check support and NOT to force server owners to allow hostname to be set...
     * or else this will simply lie and return true in future. ;-) You have been warned!
     * @param name
     */
    IsConVarOnAllowList(name: ConVarNames): boolean;

    /**
     * Sets the value of the convar. The convar must be in cfg/vscript_convar_allowlist.txt to be set. Convars marked
     * as cheat-only can be set even if sv_cheats is off. Convars marked as dev-only (i.e. not visible in console)
     * can also be set. Supported types are bool, int, float, string.
     * @warning For changes intended to persist for the whole map, set these at the start of each round instead of
     * only once. Otherwise, custom server configs may load after the initial script and not use the correct settings.
     * @param name
     * @param value
     */
    SetValue(name: ConVarNames, value: unknown): void;
}

type ConVarNames =
    ClientConVarNames |
    'bot_crouch' |
    'bot_forceattack' |
    'bot_foreceattack2' |
    'bot_forceattack_down' |
    'bot_forcefireweapon' |
    'bot_jump' |
    'bot_mimic' |
    'bot_mimic_inverse' |
    'bot_mimic_yaw_offset' |
    'bot_selectweaponslot' |
    'bot_saveme' |
    'catapult_physics_drag_boost' |
    'collision_shake_amp' |
    'collision_shake_freq' |
    'collision_shake_time' |
    'func_break_max_pieces' |
    'func_break_reduction_factor' |
    'func_breakdmg_bullet' |
    'func_breakdmg_club' |
    'func_breakdmg_explosive' |
    'mp_allowNPCs' |
    'mp_allowspectators' |
    'mp_autocrosshair' |
    'mp_autoteambalance' |
    'mp_blockstyle' |
    'mp_bonusroundtime' |
    'mp_chattime' |
    'mp_disable_respawn_times' |
    'mp_enableroundwaittime' |
    'mp_fadetoblack' |
    'mp_falldamage' |
    'mp_flashlight' |
    'mp_footsteps' |
    'mp_forceautoteam' |
    'mp_forcecamera' |
    'mp_forcerespawn' |
    'mp_friendlyfire' |
    'mp_highlander' |
    'mp_humans_must_join_team' |
    'mp_match_end_at_timelimit' |
    'mp_maxrounds' |
    'mp_respawnwavetime' |
    'mp_restartgame' |
    'mp_restartgame_immediate' |
    'mp_scrambleteams_auto' |
    'mp_scrambleteams_auto_windifference' |
    'mp_show_voice_icons' |
    'mp_spectators_restricted' |
    'mp_stalemate_enable' |
    'mp_stalemate_meleeonly' |
    'mp_stalemate_timelimit' |
    'mp_teamplay' |
    'mp_teams_unbalance_limit' |
    'mp_time_between_capscoring' |
    'mp_timelimit' |
    'mp_tournament' |
    'mp_tournament_stopwatch' |
    'mp_tournament_whitelist' |
    'mp_waitingforplayers_cancel' |
    'mp_waitingforplayers_restart' |
    'mp_waitingforplayers_time' |
    'mp_weaponstay' |
    'mp_windifference' |
    'mp_windifference_min' |
    'mp_winlimit' |
    'obj_damage_factor' |
    'obj_sapper_amount' |
    'old_radiusdamage' |
    'phys_impactforcescale' |
    'phys_pushscale' |
    'phys_stressbodyweights' |
    'phys_timescale' |
    'smoothstairs' |
    'spec_freeze_time' |
    'spec_freeze_traveltime' |
    'sv_accelerate' |
    'sv_airaccelerate' |
    'sv_alltalk' |
    'sv_bounce' |
    'sv_client_predict' |
    'sv_footsteps' |
    'sv_Friction' |
    'sv_gravity' |
    'sv_maxspeed' |
    'sv_maxvelocity' |
    'sv_noclipaccelerate' |
    'sv_proj_stunball_damage' |
    'sv_rollangle' |
    'sv_rollspeed' |
    'sv_specaccelerate' |
    'sv_specnoclip' |
    'sv_specspeed' |
    'sv_stepsize' |
    'sv_stopspeed' |
    'sv_turbophysics' |
    'sv_wateraccelerate' |
    'sv_waterdist' |
    'sv_waterfriction' |
    'tf_airblast_cray' |
    'tf_airblast_cray_debug' |
    'tf_airblast_cray_ground_minz' |
    'tf_airblast_cray_ground_reflect' |
    'tf_airblast_cray_lose_footing_duration' |
    'tf_airblast_cray_pitch_control' |
    'tf_airblast_cray_power' |
    'tf_airblast_cray_power_relative' |
    'tf_airblast_cray_reflect_coeff' |
    'tf_airblast_cray_reflect_cost_coeff' |
    'tf_airblast_cray_reflect_relative' |
    'tf_airblast_cray_stun_amount' |
    'tf_airblast_cray_stun_duration' |
    'tf_allow_player_use' |
    'tf_allow_sliding_taunt' |
    'tf_allow_taunt_switch' |
    'tf_always_loser' |
    'tf_archer_proxy_fire_rate' |
    'tf_arena_change_limit' |
    'tf_arena_first_blood' |
    'tf_arena_force_class' |
    'tf_arena_max_streak' |
    'tf_arena_override_cap_enable_time' |
    'tf_arena_override_team_size' |
    'tf_arena_preround_time' |
    'tf_arena_round_time' |
    'tf_arena_use_queue' |
    'tf_avoidteammates' |
    'tf_avoidteammates_pushaway' |
    'tf_base_boss_max_turn_rate' |
    'tf_base_boss_speed' |
    'tf_birthday' |
    'tf_birthday_ball_chance' |
    'tf_bison_tick_time' |
    'tf_boost_drain_time' |
    'tf_bot_always_full_reload' |
    'tf_bot_ammo_search_range' |
    'tf_bot_arrow_elevation_rate' |
    'tf_bot_auto_vacate' |
    'tf_bot_ballistic_elevation_rate' |
    'tf_bot_capture_seek_and_destroy_max_duration' |
    'tf_bot_capture_seek_and_destroy_min_duration' |
    'tf_bot_cart_push_radius' |
    'tf_bot_choose_target_interval' |
    'tf_bot_count' |
    'tf_bot_defend_owned_point_percent' |
    'tf_bot_defense_debug' |
    'tf_bot_defense_must_defend_time' |
    'tf_bot_difficulty' |
    'tf_bot_engineer_building_health_multiplier' |
    'tf_bot_engineer_exit_near_sentry_range' |
    'tf_bot_engineer_max_sentry_travel_distance_to_point' |
    'tf_bot_engineer_mvm_hint_min_distance_from_bomb' |
    'tf_bot_engineer_mvm_sentry_hint_bomb_backward_range' |
    'tf_bot_engineer_mvm_sentry_hint_bomb_forward_range' |
    'tf_bot_engineer_retaliate_range' |
    'tf_bot_escort_range' |
    'tf_bot_fetch_lost_flag_time' |
    'tf_bot_fire_weapon_' |
    'tf_bot_fire_weapon_min_time' |
    'tf_bot_flag_escort_give_up_range' |
    'tf_bot_flag_escort_max_count' |
    'tf_bot_flag_escort_range' |
    'tf_bot_flag_kill_on_touch' |
    'tf_bot_force_class' |
    'tf_bot_force_jump' |
    'tf_bot_formation_debug' |
    'tf_bot_health_critical_ratio' |
    'tf_bot_health_ok_ratio' |
    'tf_bot_health_search_far_range' |
    'tf_bot_health_search_near_range' |
    'tf_bot_hitscan_range_limit' |
    'tf_bot_join_after_player' |
    'tf_bot_keep_class_after_death' |
    'tf_bot_max_grenade_launch_at_sentry_range' |
    'tf_bot_max_point_defend_range' |
    'tf_bot_max_setup_gate_defend_range' |
    'tf_bot_max_sticky_launch_at_sentry_range' |
    'tf_bot_max_teleport_entrance_travel' |
    'tf_bot_max_teleport_exit_travel_to_point' |
    'tf_bot_medic_cover_test_resolution' |
    'tf_bot_medic_debug' |
    'tf_bot_medic_max_call_response_range' |
    'tf_bot_medic_max_heal_range' |
    'tf_bot_medic_start_follow_range' |
    'tf_bot_medic_stop_follow_range' |
    'tf_bot_melee_attack_abandon_range' |
    'tf_bot_melee_only' |
    'tf_bot_min_setup_gate_defend_range' |
    'tf_bot_min_setup_gate_sniper_defend_range' |
    'tf_bot_min_teleport_travel' |
    'tf_bot_near_point_travel_distance' |
    'tf_bot_notice_backstab_chance' |
    'tf_bot_notice_backstab_max_range' |
    'tf_bot_notice_backstab_min_range' |
    'tf_bot_notice_gunfire_range' |
    'tf_bot_notice_quiet_gunfire_range' |
    'tf_bot_npc_archer_arrow_damage' |
    'tf_bot_npc_archer_health' |
    'tf_bot_npc_archer_shoot_interval' |
    'tf_bot_npc_archer_speed' |
    'tf_bot_offense_must_push_time' |
    'tf_bot_offline_practice' |
    'tf_bot_path_lookahead_range' |
    'tf_bot_payload_guard_range' |
    'tf_bot_prefix_name_with_difficulty' |
    'tf_bot_pyro_always_reflect' |
    'tf_bot_pyro_deflect_tolerance' |
    'tf_bot_pyro_shove_away_range' |
    'tf_bot_quota' |
    'tf_bot_quota_mode' |
    'tf_bot_reevaluate_class_in_spawnroom' |
    'tf_bot_retreat_to_cover_range' |
    'tf_bot_sniper_aim_error' |
    'tf_bot_sniper_aim_steady_rate' |
    'tf_bot_sniper_allow_opportunistic' |
    'tf_bot_sniper_choose_target_interval' |
    'tf_bot_sniper_flee_range' |
    'tf_bot_sniper_goal_entity_move_tolerance' |
    'tf_bot_sniper_linger_time' |
    'tf_bot_sniper_melee_range' |
    'tf_bot_sniper_patience_duration' |
    'tf_bot_sniper_personal_space_range' |
    'tf_bot_sniper_spot_epsilon' |
    'tf_bot_sniper_spot_max_count' |
    'tf_bot_sniper_spot_min_range' |
    'tf_bot_sniper_spot_point_tolerance' |
    'tf_bot_sniper_spot_search_count' |
    'tf_bot_sniper_target_linger_duration' |
    'tf_bot_spawn_use_preset_roster' |
    'tf_bot_spy_change_target_range_threshold' |
    'tf_bot_spy_knife_range' |
    'tf_bot_squad_escort_range' |
    'tf_bot_sticky_base_range' |
    'tf_bot_sticky_charge_rate' |
    'tf_bot_stickybomb_density' |
    'tf_bot_suicide_bomb_friendly_fire' |
    'tf_bot_suicide_bomb_range' |
    'tf_bot_suspect_spy_forget_cooldown' |
    'tf_bot_suspect_spy_touch_interval' |
    'tf_bot_taunt_victim_chance' |
    'tf_bot_teleport_build_surface_normal_limit' |
    'tf_bot_wait_in_cover_max_time' |
    'tf_bot_wait_in_cover_min_time' |
    'tf_caplinear' |
    'tf_cheapobjects' |
    'tf_clamp_airducks' |
    'tf_clamp_back_speed' |
    'tf_clamp_back_speed_min' |
    'tf_classlimit' |
    'tf_construction_build_rate_multiplier' |
    'tf_ctf_bonus_time' |
    'tf_damage_disablespread' |
    'tf_damage_events_track_for' |
    'tf_damage_multiplier_blue' |
    'tf_damage_multiplier_red' |
    'tf_damage_range' |
    'tf_damageforcescale_other' |
    'tf_damageforcescale_pyro_jump' |
    'tf_damageforcescale_self_soldier_badrj' |
    'tf_damageforcescale_self_soldier_rj' |
    'tf_damagescale_self_soldier' |
    'tf_demoman_charge_drain_time' |
    'tf_demoman_charge_frametime_scaling' |
    'tf_demoman_charge_regen_rate' |
    'tf_deploying_bomb_delay_time' |
    'tf_deploying_bomb_time' |
    'tf_double_donk_window' |
    'tf_dropped_weapon_lifetime' |
    'tf_escort_recede_time' |
    'tf_escort_recede_time_overtime' |
    'tf_escort_score_rate' |
    'tf_eyeball_boss_acceleration' |
    'tf_eyeball_boss_attack_range' |
    'tf_eyeball_boss_health_at_level_2' |
    'tf_eyeball_boss_health_base' |
    'tf_eyeball_boss_health_per_level' |
    'tf_eyeball_boss_health_per_player' |
    'tf_eyeball_boss_horiz_damping' |
    'tf_eyeball_boss_hover_height' |
    'tf_eyeball_boss_lifetime' |
    'tf_eyeball_boss_lifetime_spell' |
    'tf_eyeball_boss_speed' |
    'tf_eyeball_boss_vert_damping' |
    'tf_fall_damage_disablespread' |
    'tf_fastbuild' |
    'tf_feign_death_activate_damage_scale' |
    'tf_feign_death_damage_scale' |
    'tf_feign_death_duration' |
    'tf_feign_death_speed_duration' |
    'tf_fireball_airblast_recharge_penalty' |
    'tf_fireball_burn_duration' |
    'tf_fireball_burning_bonus' |
    'tf_fireball_damage' |
    'tf_fireball_distance' |
    'tf_fireball_draw_debug_radius' |
    'tf_fireball_hit_recharge_boost' |
    'tf_fireball_max_lifetime' |
    'tf_fireball_radius' |
    'tf_fireball_speed' |
    'tf_flag_caps_per_round' |
    'tf_flag_return_on_touch' |
    'tf_flag_return_time_credit_factor' |
    'tf_flame_dmg_mode_dist' |
    'tf_flamethrower_boxsize' |
    'tf_flamethrower_burst_zvelocity' |
    'tf_flamethrower_burstammo' |
    'tf_flamethrower_drag' |
    'tf_flamethrower_flametime' |
    'tf_flamethrower_float' |
    'tf_flamethrower_maxdamagedist' |
    'tf_flamethrower_new_flame_offset' |
    'tf_flamethrower_shortrangedamagemultiplier' |
    'tf_flamethrower_vecrand' |
    'tf_flamethrower_velocity' |
    'tf_flamethrower_velocityfadeend' |
    'tf_flamethrower_velocityfadestart' |
    'tf_force_holidays_off' |
    'tf_forced_holiday' |
    'tf_ghost_up_speed' |
    'tf_ghost_xy_speed' |
    'tf_grapplinghook_acceleration' |
    'tf_grapplinghook_dampening' |
    'tf_grapplinghook_enable' |
    'tf_grapplinghook_fire_delay' |
    'tf_grapplinghook_follow_distance' |
    'tf_grapplinghook_jump_up_speed' |
    'tf_grapplinghook_los_force_detach_time' |
    'tf_grapplinghook_max_distance' |
    'tf_grapplinghook_medic_latch_speed_scale' |
    'tf_grapplinghook_move_speed' |
    'tf_grapplinghook_prevent_fall_damage' |
    'tf_grapplinghook_projectile_speed' |
    'tf_grapplinghook_use_acceleration' |
    'tf_gravetalk' |
    'tf_grenade_force_sleeptime' |
    'tf_grenade_forcefrom_blast' |
    'tf_grenade_forcefrom_buckshot' |
    'tf_grenade_forcefrom_bullet' |
    'tf_grenadelauncher_chargescale' |
    'tf_grenadelauncher_livetime' |
    'tf_grenadelauncher_min_contact_speed' |
    'tf_halloween_allow_ghost_hit_by_kart_delay' |
    'tf_halloween_allow_truce_during_boss_event' |
    'tf_halloween_boss_spawn_interval' |
    'tf_halloween_boss_spawn_interval_variation' |
    'tf_halloween_bot_attack_range' |
    'tf_halloween_bot_chase_duration' |
    'tf_halloween_bot_chase_range' |
    'tf_halloween_bot_health_base' |
    'tf_halloween_bot_health_per_player' |
    'tf_halloween_bot_min_player_count' |
    'tf_halloween_bot_quit_range' |
    'tf_halloween_bot_speed' |
    'tf_halloween_bot_speed_recovery_rate' |
    'tf_halloween_bot_terrify_radius' |
    'tf_halloween_eyeball_boss_spawn_interval' |
    'tf_halloween_eyeball_boss_spawn_interval_variation' |
    'tf_halloween_giant_health_scale' |
    'tf_halloween_gift_lifetime' |
    'tf_halloween_hhh_attack_kart_radius' |
    'tf_halloween_kart_air_turn_scale' |
    'tf_halloween_kart_aircontrol' |
    'tf_halloween_kart_bomb_head_damage_scale' |
    'tf_halloween_kart_bomb_head_impulse_scale' |
    'tf_halloween_kart_bombhead_scale' |
    'tf_halloween_kart_boost_duration' |
    'tf_halloween_kart_boost_impact_force' |
    'tf_halloween_kart_boost_recharge' |
    'tf_halloween_kart_brake_accel' |
    'tf_halloween_kart_brake_speed' |
    'tf_halloween_kart_coast_accel' |
    'tf_halloween_kart_damage_to_force' |
    'tf_halloween_kart_dash_accel' |
    'tf_halloween_kart_dash_speed' |
    'tf_halloween_kart_fast_turn_accel_speed' |
    'tf_halloween_kart_fast_turn_speed' |
    'tf_halloween_kart_idle_speed' |
    'tf_halloween_kart_impact_air_scale' |
    'tf_halloween_kart_impact_bounds_scale' |
    'tf_halloween_kart_impact_damage' |
    'tf_halloween_kart_impact_feedback' |
    'tf_halloween_kart_impact_force' |
    'tf_halloween_kart_impact_lookahead' |
    'tf_halloween_kart_impact_rate' |
    'tf_halloween_kart_normal_accel' |
    'tf_halloween_kart_normal_speed' |
    'tf_halloween_kart_punting_ghost_force_scale' |
    'tf_halloween_kart_return_turn_accell' |
    'tf_halloween_kart_reverse_speed' |
    'tf_halloween_kart_reverse_turn_speed' |
    'tf_halloween_kart_rocketspell_force' |
    'tf_halloween_kart_rocketspell_lifetime' |
    'tf_halloween_kart_rocketspell_speed' |
    'tf_halloween_kart_slow_turn_accel_speed' |
    'tf_halloween_kart_slow_turn_speed' |
    'tf_halloween_kart_slowmoving_accel' |
    'tf_halloween_kart_slowmoving_threshold' |
    'tf_halloween_kart_stationary_turn_speed' |
    'tf_halloween_kart_stun_amount' |
    'tf_halloween_kart_stun_duration_scale' |
    'tf_halloween_kart_stun_enabled' |
    'tf_halloween_kart_turning_curve_peak_position' |
    'tf_halloween_unlimited_spells' |
    'tf_halloween_zombie_damage' |
    'tf_halloween_zombie_mob_enabled' |
    'tf_halloween_zombie_mob_spawn_count' |
    'tf_halloween_zombie_mob_spawn_interval' |
    'tf_helpme_range' |
    'tf_invuln_time' |
    'tf_item_based_forced_holiday' |
    'tf_max_active_zombie' |
    'tf_max_charge_speed' |
    'tf_max_health_boost' |
    'tf_max_voice_speak_delay' |
    'tf_maxhealth_drain_deploy_cost' |
    'tf_maxhealth_drain_hp_min' |
    'tf_medieval' |
    'tf_medieval_autorp' |
    'tf_meleeattackforcescale' |
    'tf_merasmus_attack_range' |
    'tf_merasmus_bomb_head_duration' |
    'tf_merasmus_bomb_head_per_team' |
    'tf_merasmus_chase_duration' |
    'tf_merasmus_chase_range' |
    'tf_merasmus_disguise_debug' |
    'tf_merasmus_health_base' |
    'tf_merasmus_health_per_player' |
    'tf_merasmus_health_regen_rate' |
    'tf_merasmus_lifetime' |
    'tf_merasmus_min_player_count' |
    'tf_merasmus_min_props_to_reveal' |
    'tf_merasmus_prop_health' |
    'tf_merasmus_should_disguise_threshold' |
    'tf_merasmus_spawn_interval' |
    'tf_merasmus_spawn_interval_variation' |
    'tf_merasmus_speed' |
    'tf_merasmus_speed_recovery_rate' |
    'tf_merasmus_stun_duration' |
    'tf_minigame_suddendeath_time' |
    'tf_movement_aircurrent_aircontrol_mult' |
    'tf_movement_aircurrent_friction_mult' |
    'tf_movement_lost_footing_friction' |
    'tf_movement_lost_footing_restick' |
    'tf_mvm_bot_allow_flag_carrier_to_fight' |
    'tf_mvm_bot_flag_carrier_health_regen' |
    'tf_mvm_bot_flag_carrier_interval_to_1st_upgrade' |
    'tf_mvm_bot_flag_carrier_interval_to_2nd_upgrade' |
    'tf_mvm_bot_flag_carrier_interval_to_3rd_upgrade' |
    'tf_mvm_bot_flag_carrier_movement_penalty' |
    'tf_mvm_bot_sniper_target_by_dps' |
    'tf_mvm_buybacks_method' |
    'tf_mvm_buybacks_per_wave' |
    'tf_mvm_currency_bonus_ratio_max' |
    'tf_mvm_currency_bonus_ratio_min' |
    'tf_mvm_death_penalty' |
    'tf_mvm_default_sentry_buster_damage_dealt_threshold' |
    'tf_mvm_default_sentry_buster_kill_threshold' |
    'tf_mvm_disconnect_on_victory' |
    'tf_mvm_endless_bomb_reset' |
    'tf_mvm_endless_bot_cash' |
    'tf_mvm_endless_force_on' |
    'tf_mvm_endless_tank_boost' |
    'tf_mvm_endless_wait_time' |
    'tf_mvm_engineer_teleporter_uber_duration' |
    'tf_mvm_min_players_to_start' |
    'tf_mvm_miniboss_scale' |
    'tf_mvm_notice_sapped_squadmates_delay' |
    'tf_mvm_respec_credit_goal' |
    'tf_mvm_respec_enabled' |
    'tf_mvm_respec_limit' |
    'tf_mvm_victory_disconnect_time' |
    'tf_mvm_victory_reset_time' |
    'tf_nav_combat_build_rate' |
    'tf_nav_combat_decay_rate' |
    'tf_nav_in_combat_duration' |
    'tf_nav_in_combat_range' |
    'tf_obj_build_rotation_speed' |
    'tf_obj_damage_tank_achievement_amount' |
    'tf_obj_gib_maxspeed' |
    'tf_obj_gib_velocity_max' |
    'tf_obj_gib_velocity_min' |
    'tf_obj_ground_clearance' |
    'tf_obj_max_attach_dist' |
    'tf_obj_upgrade_per_hit' |
    'tf_overtime_nag' |
    'tf_parachute_aircontrol' |
    'tf_parachute_deploy_toggle_' |
    'tf_parachute_gravity' |
    'tf_parachute_maxspeed_onfire_z' |
    'tf_parachute_maxspeed_xy' |
    'tf_parachute_maxspeed_z' |
    'tf_passtime_ball_damping_scale' |
    'tf_passtime_ball_drag_coefficient' |
    'tf_passtime_ball_inertia_scale' |
    'tf_passtime_ball_mass' |
    'tf_passtime_ball_model' |
    'tf_passtime_ball_reset_time' |
    'tf_passtime_ball_rotdamping_scale' |
    'tf_passtime_ball_seek_range' |
    'tf_passtime_ball_seek_speed_factor' |
    'tf_passtime_ball_sphere_collision' |
    'tf_passtime_ball_sphere_radius' |
    'tf_passtime_ball_takedamage' |
    'tf_passtime_ball_takedamage_force' |
    'tf_passtime_experiment_autopass' |
    'tf_passtime_experiment_instapass' |
    'tf_passtime_experiment_instapass_charge' |
    'tf_passtime_experiment_telepass' |
    'tf_passtime_flinch_boost' |
    'tf_passtime_mode_homing_lock_sec' |
    'tf_passtime_mode_homing_speed' |
    'tf_passtime_overtime_idle_sec' |
    'tf_passtime_pack_hp_per_sec' |
    'tf_passtime_pack_range' |
    'tf_passtime_pack_speed' |
    'tf_passtime_player_reticles_enemies' |
    'tf_passtime_player_reticles_friends' |
    'tf_passtime_powerball_airtimebonus' |
    'tf_passtime_powerball_decay_delay' |
    'tf_passtime_powerball_decayamount' |
    'tf_passtime_powerball_decaysec' |
    'tf_passtime_powerball_decaysec_neutral' |
    'tf_passtime_powerball_maxairtimebonus' |
    'tf_passtime_powerball_passpoints' |
    'tf_passtime_powerball_threshold' |
    'tf_passtime_save_stats' |
    'tf_passtime_score_crit_sec' |
    'tf_passtime_scores_per_round' |
    'tf_passtime_speedboost_on_get_ball_time' |
    'tf_passtime_steal_on_melee' |
    'tf_passtime_teammate_steal_time' |
    'tf_passtime_throwarc_demoman' |
    'tf_passtime_throwarc_engineer' |
    'tf_passtime_throwarc_heavy' |
    'tf_passtime_throwarc_medic' |
    'tf_passtime_throwarc_pyro' |
    'tf_passtime_throwarc_scout' |
    'tf_passtime_throwarc_sniper' |
    'tf_passtime_throwarc_soldier' |
    'tf_passtime_throwarc_spy' |
    'tf_passtime_throwspeed_demoman' |
    'tf_passtime_throwspeed_engineer' |
    'tf_passtime_throwspeed_heavy' |
    'tf_passtime_throwspeed_medic' |
    'tf_passtime_throwspeed_pyro' |
    'tf_passtime_throwspeed_scout' |
    'tf_passtime_throwspeed_sniper' |
    'tf_passtime_throwspeed_soldier' |
    'tf_passtime_throwspeed_spy' |
    'tf_passtime_throwspeed_velocity_scale' |
    'tf_pipebomb_deflect_reset_time' |
    'tf_pipebomb_force_to_move' |
    'tf_player_drop_bonus_ducks' |
    'tf_player_movement_restart_freeze' |
    'tf_player_spell_drop_on_death_rate' |
    'tf_playergib' |
    'tf_populator_active_buffer_range' |
    'tf_populator_damage_multiplier' |
    'tf_populator_health_multiplier' |
    'tf_powerup_max_charge_time' |
    'tf_powerup_mode' |
    'tf_powerup_mode_dominant_multiplier' |
    'tf_powerup_mode_imbalance_consecutive_min_players' |
    'tf_powerup_mode_imbalance_consecutive_time' |
    'tf_powerup_mode_imbalance_delta' |
    'tf_powerup_mode_killcount_timer_length' |
    'tf_preround_push_from_damage_enable' |
    'tf_rd_max_points_override' |
    'tf_rd_min_points_to_steal' |
    'tf_rd_points_approach_interval' |
    'tf_rd_points_per_approach' |
    'tf_rd_points_per_steal' |
    'tf_rd_return_max_time' |
    'tf_rd_return_min_time' |
    'tf_rd_robot_attack_notification_cooldown' |
    'tf_rd_robot_repair_rate' |
    'tf_rd_steal_rate' |
    'tf_resolve_stuck_players' |
    'tf_rocketpack_airborne_launch_absvelocity_preserved' |
    'tf_rocketpack_cost' |
    'tf_rocketpack_delay_launch' |
    'tf_rocketpack_impact_push_max' |
    'tf_rocketpack_impact_push_min' |
    'tf_rocketpack_launch_absvelocity_preserved' |
    'tf_rocketpack_launch_delay' |
    'tf_rocketpack_launch_push' |
    'tf_rocketpack_refire_delay' |
    'tf_rocketpack_toggle_duration' |
    'tf_scout_air_dash_count' |
    'tf_scout_bat_launch_delay' |
    'tf_scout_energydrink_activation' |
    'tf_scout_energydrink_consume_rate' |
    'tf_scout_energydrink_regen_rate' |
    'tf_scout_hype_mod' |
    'tf_scout_hype_pep_max' |
    'tf_scout_hype_pep_min_damage' |
    'tf_scout_hype_pep_mod' |
    'tf_scout_stunball_base_duration' |
    'tf_scout_stunball_base_speed' |
    'tf_select_ambush_areas_close_range' |
    'tf_select_ambush_areas_max_enemy_exposure_area' |
    'tf_select_ambush_areas_radius' |
    'tf_sentrygun_ammocheat' |
    'tf_sentrygun_damage' |
    'tf_sentrygun_kill_after_redeploy_time_achievement' |
    'tf_sentrygun_max_absorbed_damage_while_controlled_for_achievement' |
    'tf_sentrygun_metal_per_rocket' |
    'tf_sentrygun_metal_per_shell' |
    'tf_sentrygun_mini_damage' |
    'tf_sentrygun_newtarget_dist' |
    'tf_sentrygun_notarget' |
    'tf_show_actor_potential_visibility' |
    'tf_show_blocked_areas' |
    'tf_show_bomb_drop_areas' |
    'tf_show_control_points' |
    'tf_show_enemy_invasion_areas' |
    'tf_show_gate_defense_areas' |
    'tf_show_in_combat_areas' |
    'tf_show_incursion_flow' |
    'tf_show_incursion_flow_gradient' |
    'tf_show_incursion_flow_range' |
    'tf_show_incursion_range' |
    'tf_show_incursion_range_max' |
    'tf_show_incursion_range_min' |
    'tf_show_mesh_decoration' |
    'tf_show_mesh_decoration_manual' |
    'tf_show_point_defense_areas' |
    'tf_show_sentry_danger' |
    'tf_show_sniper_areas' |
    'tf_show_sniper_areas_safety_range' |
    'tf_show_train_path' |
    'tf_soccer_ball_min_speed' |
    'tf_soccer_ball_multiplier' |
    'tf_soccer_ball_up_max' |
    'tf_soccer_front_hit_range' |
    'tf_solidobjects' |
    'tf_spawn_glows_duration' |
    'tf_spec_xray' |
    'tf_spells_enabled' |
    'tf_spy_cloak_consume_rate' |
    'tf_spy_cloak_no_attack_time' |
    'tf_spy_cloak_regen_rate' |
    'tf_spy_invis_time' |
    'tf_spy_invis_unstealth_time' |
    'tf_spy_max_cloaked_speed' |
    'tf_stalematechangeclasstime' |
    'tf_stats_nogameplaycheck' |
    'tf_stealth_damage_reduction' |
    'tf_sticky_airdet_radius' |
    'tf_sticky_radius_ramp_time' |
    'tf_target_dummy_bullet_mult' |
    'tf_target_dummy_health' |
    'tf_target_dummy_lifetime' |
    'tf_target_dummy_melee_mult' |
    'tf_target_dummy_other_mult' |
    'tf_tauntcam_fov_override' |
    'tf_teleporter_fov_start' |
    'tf_teleporter_fov_time' |
    'tf_tournament_classchange_' |
    'tf_tournament_classchange_ready_' |
    'tf_tournament_classlimit_demoman' |
    'tf_tournament_classlimit_engineer' |
    'tf_tournament_classlimit_heavy' |
    'tf_tournament_classlimit_medic' |
    'tf_tournament_classlimit_pyro' |
    'tf_tournament_classlimit_scout' |
    'tf_tournament_classlimit_sniper' |
    'tf_tournament_classlimit_soldier' |
    'tf_tournament_classlimit_spy' |
    'tf_tournament_hide_domination_icons' |
    'tf_use_fixed_weaponspreads' |
    'tf_useparticletracers' |
    'tf_vaccinator_uber_charge_rate_modifier' |
    'tf_weapon_criticals' |
    'tf_weapon_criticals_bucket_bottom' |
    'tf_weapon_criticals_bucket_cap' |
    'tf_weapon_criticals_bucket_default' |
    'tf_weapon_criticals_distance_falloff' |
    'tf_weapon_criticals_melee' |
    'tf_weapon_criticals_nopred' |
    'tf_weapon_minicrits_distance_falloff' |
    'tf_weapon_ragdoll_maxspeed' |
    'tf_weapon_ragdoll_velocity_max' |
    'tf_weapon_ragdoll_velocity_min' |
    'training_can_build_dispenser' |
    'training_can_build_sentry' |
    'training_can_build_tele_entrance' |
    'training_can_build_tele_exit' |
    'training_can_destroy_buildings' |
    'training_can_pickup_dispenser' |
    'training_can_pickup_sentry' |
    'training_can_pickup_tele_entrance' |
    'training_can_pickup_tele_exit' |
    'training_can_select_weapon_building' |
    'training_can_select_weapon_item1' |
    'training_can_select_weapon_item2' |
    'training_can_select_weapon_melee' |
    'training_can_select_weapon_pda' |
    'training_can_select_weapon_primary' |
    'training_can_select_weapon_secondary' |
    'weapon_medigun_charge_rate' |
    'weapon_medigun_chargerelease_rate' |
    'weapon_medigun_construction_rate' |
    'weapon_medigun_damage_modifier' |
    'weapon_medigun_resist_num_chunks' |
    'weapon_vaccinator_resist_duration' |
    string;

type ClientConVarNames =
    'cl_autoreload' |
    'cl_autorezoom' |
    'cl_flipviewmodels' |
    'cl_language' |
    'cl_spec_mode' |
    'fov_desired' |
    'hud_classautokill' |
    'hud_combattext' |
    'name' |
    'closecaption';